### ISSUE TITLE
skrypt do namespace

### ISSUE THREAD

**Issue by wareczek** [invipay/invipay-php-api#1]
@EvilVir testowaliście ten skrypt? To nie ma racji działać. Wystarczy wejść w pierwszy z brzegu plik:
https://github.com/invipay/invipay-php-api/blob/master/common/Unmarshaller.class.php#L121

Mamy użycie globalnej klasy `ReflectionClass`. Po dodaniu wpisu z namespace użycie globalnych klas wymaga poprzedzenia ich backslashem.
http://php.net/manual/pl/language.namespaces.global.php

Jaki jest sens w wspieraniu php 5.2 skoro on sam nie jest już wspierany? Dodajcie namespace domyślnie w kodzie i będzie git :)

**Comment by EvilVir** [comment]
@wareczek testowaliśmy (jeszcze drobne poprawki właśnie są dodawane) i to działa. Zobacz tutaj:

https://github.com/invipay/invipay-php-api/blob/namespaces/common/CompatibilityLayer.php#L39
https://github.com/invipay/invipay-php-api/blob/namespaces/common/CompatibilityLayer.53.php

Trick polega na tym, że w przypadku przejścia na NS'y jest zrobiona dodatkowa warstwa dziedziczenia dla tych rzeczy, których używamy z globala.

Wspieramy (nieoficjalnie) PHP 5.2 ponieważ tony oprogramowania w internetach nadal z niego korzystają, nawet stwierdzę że więcej stoi appek na PHP 5.2 niż takich, które korzystają z namespace'ów.

W każdym razie ficzer w tym branchu jeszcze się kończy robić, jak się zrobi to będzie merge do mastera.

**Comment by wareczek** [comment]
Ahhh taka akcja. Ok, czekamy na merge.

**Comment by EvilVir** [comment]
Wiesz, moje skille w PHP już trochę zardzewiały ale jedna rzecz się nigdy tutaj nie zmienia: ilość hacków i kombinacji, żeby to wszystko pospinać na tysiącach możliwych instalacji, kombinacji i wersji. Zobacz sobie jeszcze w tym CompatibilityLayer, uwierzysz że nie wszystkie instalacje PHP mają funkcje lcfirst i ucfirst? Wyszło jak klient na jakimś VPS w dzikiej serwerowni z promocji to odpalił :D

Ok, merge w każdym razie poszedł. Przetestowałem to, na tyle na ile można przetestować rozwiązanie robione w tak krótkim czasie, i wygląda na to że działa. Jakby coś było nie teges, to oczywiście zgłaszaj i będziemy fixować.
